modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="lightmanscurrency"
version="${file.jarVersion}"
displayName="Lightman's Currency"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="lightman_icon.png"
# A text field displayed in the mod UI
credits="Thanks for this example mod goes to Java" #optional
authors="Lightman314. Textures & models made by beta50test & Lightman314."
# The description text for the mod (multi line!) (#mandatory)
description="Adds a simple money & shop system to the game."

[[dependencies.lightmanscurrency]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.lightmanscurrency]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightmanscurrency]]
    modId="curios"
    mandatory=false
    versionRange="[1.17.1-5.0.0.1,)"
    ordering="AFTER"
    side="BOTH"