modLoader="javafml"
loaderVersion="[35,)"
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="lightmanscurrency"
version="${file.jarVersion}"
displayName="Lightman's Currency"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="lightman_icon.png"
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
authors="Lightman314. Textures & models made by beta50test & Lightman314."
description="Adds a simple money & shop system to the game."

[[dependencies.lightmanscurrency]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.0.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightmanscurrency]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightmanscurrency]]
    modId="lightmansdiscord"
    mandatory=false
    versionRange="[1.18-0.1.0.0,)"
    ordering="NONE"
    side="SERVER"